# Generated by Django 5.2.17 on 2026-08-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_created_at_reservation_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
